language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

# workarround to successful build a forked version of the fzp repository
#before_install:
#  - mkdir -p $HOME/gopath/src/github.com/fritzing
#  - ln -s -T ${TRAVIS_BUILD_DIR} $HOME/gopath/src/github.com/fritzing/fzp
#  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/fritzing/fzp

install:
  - go install github.com/paulvollmer/commenttags/cmd/commenttags
  - go get ./...

script:
  - cd ${TRAVIS_BUILD_DIR}/src/go && make test
  - cd ${TRAVIS_BUILD_DIR}/bin/fzp && make test
  - cd ${TRAVIS_BUILD_DIR} && commenttags ./
